config/routes.rb
Rails.application.routes.draw do
  get 'searches/seach'
  devise_for :users
  root to: 'home#top'
  get 'home/about' => 'home#about', as: 'home_about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :bookcomments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'searches/search' => 'searches#search', as: 'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true

  validates :body, presence: true
  validates :body, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%' + content)
    else
      Book.where('title LIKE ?', '%' + content + '%')
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # 自分がフォローされる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通して自分をフォローしているuserを参照
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通して自分がフォローしているuserを参照
  has_many :followings, through: :relationships, source: :followed

  attachment :profile_image

  validates :name, length: { in: 2..20 }
  validates :name, presence: true
  validates :name, uniqueness: true

  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/bookcomments_controller.rb
class BookcommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.comments.new(comment_params)
    @comment.book_id = @book.id
    unless @comment.save
      render 'error'
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])
    @comment.destroy
    redirect_to book_path(@book.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      @books = Book.all
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = " You have updated book successfully. "
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @user = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Book.search_for(@content, @method)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      @user = current_user
      redirect_to user_path(@user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = " You have updated user successfully. "
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookcomments_helper.rb
module BookcommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>Books</h2>
<table class="table">
  <thead>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
        <td class="comments-count">コメント数: <%= book.comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model:book, local:true do |f| %>
  <div class="field">
    <label for="title">Title</label><br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <label for="body">Opinion</label><br>
    <%= f.text_area :body %>
  </div>
  <br>
    <%= f.submit ' Create Book ', class: "btn btn-success" %>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <br>
      <h1>Editing Book</h1><br>

      <% if @book.errors.any? %>
        <div id="error">
          <h3><%=@book.errors.count %>errors prohibited this book from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <%end%>
          </ul>
        </div>
      <%end%>

      <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
      <label for="title">Title</label><br>
      <%= f.text_field :title, size: '58x1' %><br>
      <br>
      <label for="body">Opinion</label><br>
      <%= f.text_area :body, size: '60x3' %><br>
      <br>
      <%= f.submit ' Update Book ', class: "btn btn-success" %>
      <% end %>
      <br>
      <p class="link">
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error">
    <h3><%=@book.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<%end%>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: current_user %>
      <%= render 'books/new', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
　　　<%= render 'books/list', books: @books %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h2>New book</h2>
  <%= form_with model:@book, local:true do |f| %>
  <div class="field">
    <label for="title">Title</label><br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <label for="body">Opinion</label><br>
    <%= f.text_area :body %>
  </div>
  <br>
    <%= f.submit ' Create Book ' %>
  <% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @book.user %>
      <%= render 'books/new', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <br>
      <h2>Book detail</h2>
        <table class="table">
          <tbody>
              <tr id="book_<%= @book.id %>">
                <td>
                  <%= link_to user_path(@book.user.id) do %>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 55, fallback: "no_image.jpg", size: '40x40' %>
                  <% end %>
                  <br>
                  <%= link_to @book.user.name, user_path(@book.user.id) %>
                </td>
                <td>
                  <%= link_to @book.title, book_path(@book.id) %>
                </td>
                <td>
                  <%= @book.body %>
                </td>
                <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
                <td class="comments-count"><p>コメント:<%= @book.comments.count %>件</p></td>
                <% if @book.user.id == current_user.id %>
                <td>
                  <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
                </td>
                <td>
                  <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %>
                </td>
                <% else %>
                <td colspan="3"></td>
                <td></td>
                <td></td>
                <% end %>
              </tr>
          </tbody>
        </table>
        <table class="book_comments">
          <%= render "bookcomments/comments", book: @book %>
        </table>
        <div>
          <%= form_with model:[@book,@comment], url: book_bookcomments_path(@book.id), remote: true do |f| %>
            <%= f.text_area :comment, size:"90x5" %><br>
            <%= f.submit "送信" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/home/about.html.erb
<div class="container"><br>
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6"><br>
      <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In<i class="fas fa-book"></i><strong>bookers</strong>,</p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<br>
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 63, 63, fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>Name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= user.followings.count %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= user.followers.count %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationship_path(user.id), method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-succuess" %>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' do %><% end %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <br>
      <h1>User info</h1>

      <% if @user.errors.any? %>
        <div id="error">
          <h3><%=@user.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <%end%>
          </ul>
        </div>
      <%end%>

      <%= form_with model:@user, local:true do |f| %>
      <div class="field">
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name", size: "58x1" %>
      </div>
      <br>
      <div class="field">
        <label for="inputImage">Image</label><br>
        <%= f.attachment_field :profile_image, placeholder: "Image" %>
      </div>
      <br>
      <div class="field">
        <label for="inputIntroduction">Introduction</label><br>
        <%= f.text_area :introduction, autofocus:true, id:"inputIntroduction", placeholder:"Introduction", size: "60x3" %>
      </div>
      <br>
      <%= f.submit ' Update User ', class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: current_user %>
      <%= render 'books/new', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      </br>
      <h2>Users</h2>
        <table class="table">
          <thead>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to "Show", user_path(user.id) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <%= render 'books/new', book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
　　　<%= render 'books/list', books: @books %>
    </div>
  </div>
</div>